name: Testing

on: [push]

jobs:
  tests:
    name: "Tests"

    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}

    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        os: [ubuntu-latest, ubuntu-18.04]
        php-version: ["8.0", "8.1"]
        experimental: [false]
        include:
          - php-version: "8.2"
            os: ubuntu-latest
            experimental: true

    steps:
      - name: "Install PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php-version }}"
          coverage: xdebug3

      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Install dependencies"
        run: composer install --prefer-dist --no-progress

      - name: "Check Code Style"
        run: vendor/bin/phpcs

      - name: "Run PHP Static Analysis Tool"
        run: vendor/bin/phpstan

      - name: "Run PHPUnit tests"
        run: vendor/bin/phpunit --coverage-clover=coverage.xml

      - name: "Run Infection mutation tests"
        run: vendor/bin/infection --min-covered-msi=99 --min-msi=99
        env:
          INFECTION_DASHBOARD_API_KEY: ${{ secrets.INFECTION_DASHBOARD_API_KEY }}

      - name: "Send coverage to codecov.io"
        uses: codecov/codecov-action@v1
        if: matrix.experimental == false
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
